### PR TITLE
Fix syntax error

### PR DESCRIPTION
**Pull request by ocefpaf**
@ChrisBarker-NOAA there is a missing `)` in line 299.  The rest is white space noise.

(Sorry, my text editor is configured to remove leading/blank spaces.  I can change that and rebase if you want.)

### CODE REVIEW

**Comment by ChrisBarker-NOAA** [comment]
Thanks Filipe -- but don't put too much effort into these -- they are prototyp-level at best, as you can tell :-)

**Comment by ChrisBarker-NOAA** [comment]
No problem with the whitespace noise -- nice to get that cleaned up.

**Comment by ocefpaf** [comment]
>  they are prototype-level at best, as you can tell :-)

Don't worry.  I just did what @rsignell-usgs needed.  (I am not a user of gnome and friends.)

**Comment by ChrisBarker-NOAA** [comment]
Well, @rsignell-usgs -- yo ushould know know to expect these to work. I honestly can't remember what state I left the nc to kml script in -- and that would be useful.

py_gnome can output kml now, too. But you may need to wait for a newer version. which should be today.

**Pull request merged**
